### ISSUE TITLE
The range of 'w' values in the algorithm

### ISSUE THREAD

**Issue by Piao-Hu** [OptMN-Lab/fairgrad#2]
Hello, your job is great, but I am still confused about the gradient weighting coefficient w mentioned in your algorithm. Does this w not need to be limited to a total of 1?

**Comment by bhsimon0810** [comment]
Thanks for reaching out. Yes, in our algorithm we only consider $w=(w_1,\cdots,w_K)\in\mathbb{R}_{+}^K$ with each element being positive. We do not restrict $w$ in a simplex where $\sum_i w_i=1$. Similar considerations can also be found in [Nash-MTL](https://arxiv.org/abs/2202.01017).

**Comment by bhsimon0810** [comment]
Close the issue :)
